import type { Metadata } from "next";
import Link from "next/link";
import { Eyebrow, Shell } from "../../components";

const title = "Geometry–Induced Contraction Degradation and Stabilization of Learning-Enabled Observers";
const description = "Accepted for presentation at IEEE CDC 2026; proceedings publication forthcoming.";
const base = process.env.NEXT_PUBLIC_SITE_URL || "https://afleck18.github.io/andrew-fleck-portfolio";
const url = `${base}/publications/geometry-induced-observers/`;

export const metadata: Metadata = { title, description, alternates: { canonical: url }, openGraph: { title, description, url, type: "article" }, twitter: { card: "summary", title, description } };

export default function GeometryInducedObservers() {
  return <Shell><article className="paper-detail">
    <header className="paper-header"><Eyebrow>Accepted paper · CDC 2026</Eyebrow><h1>{title}</h1><p className="paper-authors">Aditi Acharya and Andrew Fleck</p><p className="acceptance-note">Accepted for presentation at the 65th IEEE Conference on Decision and Control (CDC 2026). The IEEE proceedings version is forthcoming.</p><div className="publication-actions"><a className="button" href="https://arxiv.org/abs/2608.14925" target="_blank" rel="noopener noreferrer" aria-label="View the paper on arXiv">Paper ↗</a><a href="https://arxiv.org/pdf/2608.14925" target="_blank" rel="noopener noreferrer" aria-label="Download the arXiv PDF">arXiv PDF ↗</a><a href="https://doi.org/10.48550/arXiv.2608.14925" target="_blank" rel="noopener noreferrer" aria-label="Open the arXiv DOI record">arXiv DOI ↗</a></div></header>
    <section className="paper-layout"><aside><dl><div><dt>Conference</dt><dd>IEEE CDC 2026</dd></div><div><dt>Location</dt><dd>Honolulu, Hawaii</dd></div><div><dt>Session</dt><dd>FrAT6.8</dd></div><div><dt>Status</dt><dd>Accepted; proceedings publication forthcoming</dd></div><div><dt>arXiv</dt><dd>2608.14925 · eess.SY</dd></div></dl></aside><div className="paper-body"><section><h2>Abstract</h2><p>Learned perception models increasingly serve as measurement maps within nonlinear observers. Their state-dependent Jacobians introduce measurement geometry that measurement-value accuracy does not constrain. Even when measurements satisfy standard accuracy criteria, the corresponding one-step Euclidean error operator can be noncontractive. Improving measurement accuracy or retuning the correction strength may leave this observer-level contraction failure unresolved. We derive the exact estimation-error operator and use it to determine whether scalar-gain adjustment can restore contraction or the correction structure must change. The analysis separates three distinct cases: a conservative certificate may be inconclusive, the nominal gain may be exactly noncontractive, or the correction geometry may lie beyond scalar-gain repair. Convexity makes this recovery boundary exactly computable. When scalar recovery remains possible, uncertainty-aware envelopes define a safe projection that changes the nominal gain only when contraction and same-state improvement are certified. Uniform local certification yields exponential error decay and explicit disturbance-dependent bounds. The method uses local composite-Jacobian information or a certified approximation and requires no retraining. Scalar experiments demonstrate certified contraction recovery and improved tracking when the geometry permits. Controlled real-image experiments provide numerical evidence of scalar-unrecoverable contraction loss despite accurate learned measurements.</p></section><section><h2>Citation</h2><p className="citation">A. Acharya and A. Fleck, “Geometry–Induced Contraction Degradation and Stabilization of Learning-Enabled Observers,” accepted for presentation at the 65th IEEE Conference on Decision and Control (CDC), 2026. Proceedings publication forthcoming. arXiv:2608.14925.</p></section><Link className="text-link" href="/publications">← All publications</Link></div></section>
  </article></Shell>;
}
