import type { Metadata } from "next";
import Link from "next/link";
import { Eyebrow, Shell } from "../../components";

const title = "Geometry–Induced Contraction Degradation and Stabilization of Learning-Enabled Observers";
const description = "Accepted for presentation at IEEE CDC 2026; proceedings publication forthcoming.";

export const metadata: Metadata = { title, description, openGraph: { title, description, type: "article" } };

export default function GeometryInducedObservers() {
  return <Shell><article className="paper-detail">
    <header className="paper-header"><Eyebrow>Accepted paper · CDC 2026</Eyebrow><h1>{title}</h1><p className="paper-authors">Aditi Acharya and Andrew Fleck</p><p className="acceptance-note">Accepted for presentation at the 65th IEEE Conference on Decision and Control (CDC 2026). The IEEE proceedings version is forthcoming.</p><div className="publication-actions"><a className="button" href="https://arxiv.org/abs/2608.14925" target="_blank" rel="noopener noreferrer" aria-label="View the paper on arXiv">Paper ↗</a><a href="https://arxiv.org/pdf/2608.14925" target="_blank" rel="noopener noreferrer" aria-label="Download the arXiv PDF">arXiv PDF ↗</a><a href="https://doi.org/10.48550/arXiv.2608.14925" target="_blank" rel="noopener noreferrer" aria-label="Open the arXiv DOI record">arXiv DOI ↗</a></div></header>
    <section className="paper-layout"><aside><dl><div><dt>Conference</dt><dd>IEEE CDC 2026</dd></div><div><dt>Location</dt><dd>Honolulu, Hawaii</dd></div><div><dt>Session</dt><dd>FrAT6.8</dd></div><div><dt>Status</dt><dd>Accepted; proceedings publication forthcoming</dd></div><div><dt>arXiv</dt><dd>2608.14925 · eess.SY</dd></div></dl></aside><div className="paper-body"><section><h2>Abstract</h2><p>Learned perception models are increasingly used as measurement maps within nonlinear observers, mapping high dimensional sensory inputs to low dimensional quantities for state estimation. Unlike analytic measurement functions, learned models introduce state dependent Jacobians whose effect on observer stability is rarely characterized. We show that learned measurement geometry enters the observer error dynamics explicitly and rescales Euclidean contraction margins.</p><p>Under fixed gains, increased measurement sensitivity reduces the certifiable contraction region and can eliminate exponential convergence guarantees. To address this effect, we introduce a representation aware gain normalization that compensates for geometry induced amplification using only local Jacobian information. The proposed approach treats the learned measurement model as a black box and requires no retraining or architectural modification.</p><p>The normalization removes the dominant sensitivity dependence and restores a uniform Euclidean contraction bound while preserving a simple observer structure. Numerical and real data experiments validate the predicted sensitivity convergence relationship and demonstrate improved robustness and stability in learning enabled observer architectures.</p></section><section><h2>Citation</h2><p className="citation">A. Acharya and A. Fleck, “Geometry–Induced Contraction Degradation and Stabilization of Learning-Enabled Observers,” accepted for presentation at the 65th IEEE Conference on Decision and Control (CDC), 2026. Proceedings publication forthcoming. arXiv:2608.14925.</p></section><Link className="text-link" href="/publications">← All publications</Link></div></section>
  </article></Shell>;
}
